// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRZaRFykFCBjbTzHTMUME27j---UsArY4',
    appId: '1:546560501115:web:c6da2933d395d2183e49de',
    messagingSenderId: '546560501115',
    projectId: 'mental-healthcare-app-project',
    authDomain: 'mental-healthcare-app-project.firebaseapp.com',
    storageBucket: 'mental-healthcare-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeYPlNIvZl6HwLVjDKSjQXhERsxmslYYc',
    appId: '1:546560501115:android:7b3185932c9ae8583e49de',
    messagingSenderId: '546560501115',
    projectId: 'mental-healthcare-app-project',
    storageBucket: 'mental-healthcare-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxEt2SmhpKZDcea99bcBrj1Aqt3P9k4CA',
    appId: '1:546560501115:ios:1a782a559ed36b1b3e49de',
    messagingSenderId: '546560501115',
    projectId: 'mental-healthcare-app-project',
    storageBucket: 'mental-healthcare-app-project.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthSupportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxEt2SmhpKZDcea99bcBrj1Aqt3P9k4CA',
    appId: '1:546560501115:ios:1a782a559ed36b1b3e49de',
    messagingSenderId: '546560501115',
    projectId: 'mental-healthcare-app-project',
    storageBucket: 'mental-healthcare-app-project.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthSupportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRZaRFykFCBjbTzHTMUME27j---UsArY4',
    appId: '1:546560501115:web:a3c3bdedbd8b81f23e49de',
    messagingSenderId: '546560501115',
    projectId: 'mental-healthcare-app-project',
    authDomain: 'mental-healthcare-app-project.firebaseapp.com',
    storageBucket: 'mental-healthcare-app-project.firebasestorage.app',
  );
}
